export interface EBooksInterface {
  img: string;
  alt: string;
  title: string;
  date: string;
  link: string;
  year: number;
  id: number;
}

export const SCI_FI_BOOK_DATA: EBooksInterface[] = [
  {
    img: '../../../../../../../assets/investments/e-books/b-1.jpg',
    alt: 'sci-fi image',
    title: 'Galactic Odyssey',
    date: 'October 1, 2023',
    link: '',
    year: 2023,
    id: 1,
  },
  {
    img: '../../../../../../../assets/investments/e-books/b-2.jpg',
    alt: 'sci-fi image',
    title: 'Quantum Chronicles',
    date: 'November 15, 2023',
    link: '',
    year: 2023,
    id: 2,
  },
  {
    img: '../../../../../../../assets/investments/e-books/b-3.jpg',
    alt: 'sci-fi image',
    title: 'Nebula Nexus',
    date: 'January 10, 2022',
    link: '',
    year: 2022,
    id: 3,
  },
  {
    img: '../../../../../../../assets/investments/e-books/b-4.jpg',
    alt: 'sci-fi image',
    title: 'Cybernetic Uprising',
    date: 'February 28, 2022',
    link: '',
    year: 2022,
    id: 4,
  },
  {
    img: '../../../../../../../assets/investments/e-books/b-5.jpg',
    alt: 'sci-fi image',
    title: 'Voyage to Andromeda',
    date: 'April 5, 2022',
    link: '',
    year: 2022,
    id: 5,
  },
  {
    img: '../../../../../../../assets/investments/e-books/b-6.jpg',
    alt: 'sci-fi image',
    title: 'Aeon Accelerator',
    date: 'May 20, 2022',
    link: '',
    year: 2022,
    id: 6,
  },
  {
    img: '../../../../../../../assets/investments/e-books/b-7.jpg',
    alt: 'sci-fi image',
    title: 'Genome of the Future',
    date: 'July 8, 2022',
    link: '',
    year: 2022,
    id: 7,
  },
  {
    img: '../../../../../../../assets/investments/e-books/b-8.jpg',
    alt: 'sci-fi image',
    title: 'The Singularity Equation',
    date: 'August 18, 2022',
    link: '',
    year: 2022,
    id: 8,
  },
  {
    img: '../../../../../../../assets/investments/e-books/b-9.jpg',
    alt: 'sci-fi image',
    title: 'Dystopian Reckoning',
    date: 'September 30, 2022',
    link: '',
    year: 2022,
    id: 9,
  },
  {
    img: '../../../../../../../assets/investments/e-books/b-10.jpg',
    alt: 'sci-fi image',
    title: 'Asteroid Alchemy',
    date: 'November 12, 2022',
    link: '',
    year: 2022,
    id: 10,
  },
  {
    img: '../../../../../../../assets/investments/e-books/b-11.jpg',
    alt: 'sci-fi image',
    title: "Time Traveler's Dilemma",
    date: 'May 5, 2021',
    link: '',
    year: 2021,
    id: 11,
  },
  {
    img: '../../../../../../../assets/investments/e-books/b-12.jpg',
    alt: 'sci-fi image',
    title: 'Robot Revolutions',
    date: 'July 12, 2021',
    link: '',
    year: 2021,
    id: 12,
  },
  {
    img: '../../../../../../../assets/investments/e-books/b-13.jpg',
    alt: 'sci-fi image',
    title: 'Alien Alliances',
    date: 'August 25, 2021',
    link: '',
    year: 2021,
    id: 13,
  },
  {
    img: '../../../../../../../assets/investments/e-books/b-14.jpg',
    alt: 'sci-fi image',
    title: 'Virtual Realms',
    date: 'October 3, 2021',
    link: '',
    year: 2021,
    id: 14,
  },
  {
    img: '../../../../../../../assets/investments/e-books/b-15.jpg',
    alt: 'sci-fi image',
    title: 'Eco-Futures',
    date: 'December 10, 2021',
    link: '',
    year: 2021,
    id: 15,
  },
  {
    img: '../../../../../../../assets/investments/e-books/b-16.jpg',
    alt: 'sci-fi image',
    title: 'Parallel Universes',
    date: 'March 2, 2021',
    link: '',
    year: 2021,
    id: 16,
  },
  {
    img: '../../../../../../../assets/investments/e-books/b-17.jpg',
    alt: 'sci-fi image',
    title: 'Galactic Diplomacy',
    date: 'April 14, 2021',
    link: '',
    year: 2021,
    id: 17,
  },
  {
    img: '../../../../../../../assets/investments/e-books/b-18.jpg',
    alt: 'sci-fi image',
    title: 'Cyberpunk Chronicles',
    date: 'June 7, 2021',
    link: '',
    year: 2021,
    id: 18,
  },
  {
    img: '../../../../../../../assets/investments/e-books/b-19.jpg',
    alt: 'sci-fi image',
    title: 'Quantum Realities',
    date: 'August 8, 2021',
    link: '',
    year: 2021,
    id: 19,
  },
  {
    img: '../../../../../../../assets/investments/e-books/b-20.jpg',
    alt: 'sci-fi image',
    title: 'Starship Pioneers',
    date: 'September 19, 2021',
    link: '',
    year: 2021,
    id: 20,
  },
];
